FloodTarget.out:	src/main.c
			gcc src/main.c src/packetsoup.c -o FloodTarget.out

clean:	
			rm -f FloodTarget.out

BuildClean:
			rm -f FloodTarget.out
			gcc src/main.c src/packetsoupt.c -o FloodTarget.out
			./FloodTarget.out