#MAKEFILE

FloodTarget:	src/main.c
			gcc src/main.c src/packetsoup.c -o FloodTarget

clean:	
			rm -f FloodTarget

cleanbuild:
			rm -f FloodTarget
			gcc src/main.c src/packetsoup.c -o FloodTarget
			./FloodTarget